### ISSUE TITLE
The install instructions via Brew are not working.

### ISSUE THREAD

**Issue by diek** [dracula/snippetslab#2]
I am getting the following error when trying to install via Brew:
```sh
Error: Invalid cask: /usr/local/Homebrew/Library/Taps/dracula/homebrew-install/Casks/dracula-alfred.rb
Cask 'dracula-alfred' is unreadable: undefined method `name' for nil:NilClass
Error: Invalid cask: /usr/local/Homebrew/Library/Taps/dracula/homebrew-install/Casks/dracula-drafts.rb
Cask 'dracula-drafts' is unreadable: undefined method `/' for nil:NilClass
Error: Cannot tap dracula/install: invalid syntax in tap!
```

**Comment by ianjukes** [comment]
I have the same issue - but get the same error whether I try to install via Brew, or by git cloning and then running generate.command. Neither is working.

**Comment by danielbayley** [comment]
@diek Should be fixed now? Please test, and report back…

**Comment by ianjukes** [comment]
@danielbayley - was I imagining things, or did I see a message about a fix? 😉 Been checking here regularly for updates. Still not working for me via homebrew or git pull.

**Comment by danielbayley** [comment]
> @danielbayley - was I imagining things, or did I see a message about a fix? 😉 Been checking here regularly for updates. Still not working for me via homebrew or git pull.

@diek @ianjukes No, it was real 😅 I pushed a fix, but wasn’t quite there… Should be working now though, so please test and report back… Thanks.

Also, be sure the tap is updated first:
~~~ sh
brew update
brew untap dracula/install --force
brew tap dracula/install
brew install --cask dracula-snippetslab
~~~

**Comment by ianjukes** [comment]
Hi @danielbayley. Still an issue here when installing by Homebrew. I followed your steps above and get the following error:

```
Error: It seems the Generic Artifact source '/opt/homebrew/Caskroom/dracula-snippetslab/latest/snippetslab-main/Dracula.json' is not there.
```

I am on a MacBook Pro with an Apple silicon processor, and Homebrew is installed under `/opt/homebrew`. Could that be anything to do with it?

Installing via `git clone` also fails when I try to run `./generate.command`. In that case I get the following error:

```
command not found: /var/folders/gk/3g_jysmd04q0pqhdf5ncf71h0000gn/T/
command not found: /var/folders/gk/3g_jysmd04q0pqhdf5ncf71h0000gn/T/
```

It does display twice. Let me know if I can do anything else to troubleshoot.

**Comment by danielbayley** [comment]
> I am on a MacBook Pro with an Apple silicon processor, and Homebrew is installed under `/opt/homebrew`. Could that be anything to do with it?

@ianjukes Probably. Unfortunately I don’t have access to one to check…

> ~~~
> command not found: /var/folders/gk/3g_jysmd04q0pqhdf5ncf71h0000gn/T/
> command not found: /var/folders/gk/3g_jysmd04q0pqhdf5ncf71h0000gn/T/
> ~~~

This looks like something to do with the use of `$TMPDIR` [here](https://github.com/dracula/snippetslab/blob/main/generate.command#L6), and displayed twice because `npx` is called twice [here](https://github.com/dracula/snippetslab/blob/main/generate.command#L17-L18). But I have no idea why this is running differently on Apple silicone…

**Comment by ianjukes** [comment]
Okay - I have an Intel iMac in my office and when I get a moment will verify that everything installs fine there. I haven't tried that yet. That will narrow things down to Apple Silicon installations. Then I'll see what I can figure out from there…

Thanks for all your help @danielbayley 😊

**Comment by ianjukes** [comment]
I'm not entirely sure what has happened, but I can confirm that the everything installs fine on my Intel iMac (running Monterey), and since upgrading to Ventura the installation also works fine on my MacBook Pro M1 Pro as well. Go figure! I think you can go ahead and close the issue.

Thanks @danielbayley! Apologies its taken me so long to check.

**Comment by kappesante** [comment]
Error: SnippetsLab is not installed. Try: mas install 1006087419

this is just NOT TRUE. snippetslab is installed, purchased, and running.

<img width="2560" alt="Screenshot 2022-12-07 alle 14 14 58" src="https://user-images.githubusercontent.com/16004367/206188673-0acb9a92-7a3b-4252-8203-56e2b144ba83.png">

**Comment by skyrkou** [comment]
> I'm not entirely sure what has happened, but I can confirm that the everything installs fine on my Intel iMac (running Monterey), and since upgrading to Ventura the installation also works fine on my MacBook Pro M1 Pro as well. Go figure! I think you can go ahead and close the issue.
> 
> Thanks @danielbayley! Apologies its taken me so long to check.

Same issue here with M2 MacBook Pro. Can you share your Dracula.json file maybe?

**Comment by kappesante** [comment]
yeah, we can share the json or even the theme file, the process is maybe unnecessary.

**Comment by skyrkou** [comment]
Can anyone share the produced json or the actual theme file itself?
